### ISSUE TITLE
Contact - uvc-gadget - collaboration

### ISSUE THREAD

**Issue by peterbay** [kinweilee/v4l2-mmal-uvc#1]
Hi.
I'm working on project uvc-gadget for raspberry pi with enhanced video controls. 
My repo is [https://github.com/peterbay/uvc-gadget](url).
It's possible to contact you by email or any other communication channel?
My email is pvavrin@gmail.com.
Petr Vavrin (peterbay)

**Comment by kinweilee** [comment]
wow my first issue! I've sent you an email.
